---
- name: restart wazuh-agent
  service: name=wazuh-agent state=restarted enabled=yes

- name: restart wazuh-agent windows
  win_service: name=OssecSvc start_mode=auto state=restarted

- name: restart wazuh-agent solaris 10
  shell: /etc/init.d/wazuh-agent restart
