---
- name: Solaris 10 | Check if the Wazuh agent is installed
  shell: pkginfo wazuh-agent | grep -c 'wazuh-agent' | xargs
  register: wazuh_agent_installed
  tags:
    - init

- name: Solaris 10 | Copy Wazuh Agent package file
  copy:
    src: "{{ wazuh_solaris10_sparc.src }}"
    dest: /tmp/wazuh-agent.pkg
    mode: 0644
  when:
    - wazuh_agent_installed.stdout == "0"
  tags:
    - init

- name: Solaris 10 | Get md5sum of the installer
  stat:
    path: /tmp/wazuh-agent.pkg
  register: sparc_installer
  when:
    - wazuh_agent_installed.stdout == "0"
  tags:
    - init

- name: Solaris 10 | Verify package checksum
  fail: msg="Wazuh Agent package checksum mismatch, exiting..."
  when:
    - wazuh_agent_installed.stdout == "0"
    - sparc_installer.stat.md5 != wazuh_solaris10_sparc.md5
  tags:
    - init

- name: Solaris 10 | Set admin file for silent installation
  template: src=solaris10-admin.j2
            dest=/tmp/wazuh-silent-install.admin
  when:
    - wazuh_agent_installed.stdout == "0"
  tags:
    - init

- name: Solaris 10 | Installing Wazuh Agent
  shell: yes all|pkgadd -n -awazuh-silent-install.admin -d wazuh-agent.pkg
  args:
    chdir: /tmp
  when:
    - wazuh_agent_installed.stdout == "0"
  tags:
    - init

- name: Solaris 10 | Check if client.keys exists
  stat: path=/var/ossec/etc/client.keys
  register: check_keys
  tags:
    - config

- name: Solaris 10 | Register agent
  shell: /var/ossec/bin/agent-auth -m {{ wazuh_manager_ip }} -p {{ wazuh_authd_port }}
  register: agent_auth_output
  when:
    - wazuh_register_client == true
    - check_keys.stat.size == 0
    - wazuh_manager_ip is not none
  tags:
    - config

- name: Solaris 10 | Verify agent registration
  shell: echo {{ agent_auth_output }} | grep "Valid key created"
  when:
    - wazuh_register_client == true
    - check_keys.stat.size == 0
    - wazuh_manager_ip is not none
  tags:
    - config

- name: Solaris 10 | Installing agent configuration (ossec.conf)
  template: src=var-ossec-etc-ossec-agent.conf.j2
            dest=/var/ossec/etc/ossec.conf
            owner=root
            group=ossec
            mode=0644
  notify: restart wazuh-agent solaris 10
  tags:
    - init
    - config

- name: Solaris 10 | Delete Wazuh Agent package file
  file:
      path: /tmp/wazuh-agent.pkg
      state: absent
  when:
    - wazuh_agent_installed.stdout == "0"
  tags:
    - init
