---
- name: Debian/Ubuntu | Install apt-transport-https and ca-certificates
  apt: name="{{ item }}" state=present update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Debian/Ubuntu | Setting webupd8 repository
  apt_repository:
    repo: 'ppa:webupd8team/java'
    codename: 'xenial'

- name: Debian/Ubuntu | Accept Oracle Java 8 license
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    value: true
    vtype: boolean

- name: Debian/Ubuntu | Oracle Java 8 installer
  apt: name=oracle-java8-installer state=present update_cache=yes
  tags: install

- name: Debian/Ubuntu | Add Elasticsearch GPG key.
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Debian/Ubuntu | Install Elastic repo
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/6.x/apt stable main'
    state: present
    filename: 'elastic_repo'

- name: Debian/Ubuntu | Install Elasticsarch
  apt: name=elasticsearch={{ elastic_stack_version }} state=present update_cache=yes
  tags: install

- name: Set use_systemd parameter
  set_fact: use_system_d={{(ansible_distribution == 'Debian' and ansible_distribution_version | version_compare('8', '>=')) or (ansible_distribution in ['RedHat','CentOS'] and ansible_distribution_version | version_compare('7', '>=')) or (ansible_distribution == 'Ubuntu' and ansible_distribution_version | version_compare('15', '>=')) }}

- name: Configure Elasticsearch System Resources.
  template:
    src: elasticsearch.j2
    dest: /etc/default/elasticsearch
    owner: root
    group: elasticsearch
    mode: 0660
  notify: restart elasticsearch
  tags: configure
  when:
    - elasticsearch_tunning == true
    - use_system_d == false
