---
- name: RedHat/CentOS/Fedora | download Oracle Java RPM
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jre-8u151-linux-x64.rpm
    dest: /tmp/jdk-8-linux-x64.rpm
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
  register: oracle_java_task_rpm_download

- name: RedHat/CentOS/Fedora | Install Oracle Java RPM
  package: name=/tmp/jdk-8-linux-x64.rpm state=present
  when: oracle_java_task_rpm_download is defined
  register: oracle_java_task_rpm_installed
  tags: install

- name: RedHat/CentOS/Fedora | Install Elastic repo
  yum_repository:
    name: elastic_repo
    description: Elastic repository for 6.x packages
    baseurl: https://artifacts.elastic.co/packages/6.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: yes

- name: RedHat/CentOS/Fedora | Install Elasticsarch
  package: name=elasticsearch-{{ elastic_stack_version }} state=present
  when: oracle_java_task_rpm_installed is defined
  tags: install

- name: Set use_sytemd parameter
  set_fact: use_system_d={{(ansible_distribution == 'Debian' and ansible_distribution_version | version_compare('8', '>=')) or (ansible_distribution in ['RedHat','CentOS'] and ansible_distribution_version | version_compare('7', '>=')) or (ansible_distribution == 'Ubuntu' and ansible_distribution_version | version_compare('15', '>=')) }}

- name: Configure Elasticsearch System Resources.
  template:
    src: elasticsearch.j2
    dest: /etc/sysconfig/elasticsearch
    owner: root
    group: elasticsearch
    mode: 0660
  notify: restart elasticsearch
  tags: configure
  when:
    - elasticsearch_tunning == true
    - use_system_d == false
